// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://welhvotkdhxzisbbqdtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlbGh2b3RrZGh4emlzYmJxZHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDgwMTksImV4cCI6MjA1ODQ4NDAxOX0.px2GTSVGUtH2u0RStkc-2UwfO44nixKnnAt9sEOiiig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);